apiVersion: apps/v1
kind: Deployment
metadata:
  name: matches-deployment
spec:
  selector:
    matchLabels:
      app: matches
  replicas: 1
  template:
    metadata:
      labels:
        app: matches
    spec:
      containers: 
        - name: matches
          image: mariosliapis/devops:1.3
          ports:
            - containerPort: 80
  